version: '3.1'
services:
  mysql:
    image: mysql:5.7
    container_name: container_mysql
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    ports:
      - $DB_PORT:3306

  api:
    image: node:latest
    container_name: container_api
    restart: always
    ports:
      - $SERVER_PORT:$SERVER_PORT
    environment:
      - DB_HOST=mysql
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - SERVER_PORT=$SERVER_PORT
    volumes:
      - ./backend:/usr/app
    working_dir: /usr/app
    command: bash -c "yarn && yarn dev"
